force-app/api/objects/CoreLibs_ApiEndpoint__mdt/CoreLibs_ApiEndpoint__mdt.object-meta.xml
<CustomObject>
    <description>Endpoint configuration for matching resolvers to endpoints.</description>
    <label>Api Endpoint</label>
    <pluralLabel>Api Endpoints</pluralLabel>
</CustomObject>

force-app/api/objects/CoreLibs_ApiEndpoint__mdt/fields/EndpointRegex__c.field-meta.xml
<CustomField>
    <fullName>EndpointRegex__c</fullName>
    <description
  >Regex pattern to match for the endpoint. For example: /v1/CaseService/close or /v1/cases/^0-9]*$.</description>
    <inlineHelpText
  >Regex pattern to match for the endpoint. For example: /v1/CaseService/close or /v1/cases/^0-9]*$.</inlineHelpText>
    <label>Endpoint Regex</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/api/objects/CoreLibs_ApiEndpoint__mdt/fields/ResolverClassName__c.field-meta.xml
<CustomField>
    <fullName>ResolverClassName__c</fullName>
    <description>Name of the apex class to act as the resolver for this endpoint.</description>
    <inlineHelpText>Name of the apex class to act as the resolver for this endpoint.</inlineHelpText>
    <label>Class Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/api/classes/CoreLibs_ApiUrlResolver.cls
/**
 * @description Resolves a given Url to the appropriate API service resolver
 * @author Tom Wilkins
 * @group API
 */
public inherited sharing class CoreLibs_ApiUrlResolver {
  @TestVisible
  private static final String ENDPOINT_NOT_FOUND = 'Endpoint: {0} not found.';
  @TestVisible
  private RestRequest req;

  /**
   * @description Constructor
   * @param req The RestRequest to process
   */
  public CoreLibs_ApiUrlResolver(RestRequest req) {
    this.req = req;
  }

  /**
   * @description Evalutes the url against configured resolvers and returns the resolver if found
   * @return ApiEndpointResolver
   * @throw {@link CoreLibs_ApiExceptions.NotFoundException} if the resolver does not exist
   */
  public CoreLibs_ApiEndpointResolver resolve() {
    CoreLibs_ApiEndpointSelector selector = (CoreLibs_ApiEndpointSelector) CoreLibs_Factories.selector.create(
        CoreLibs_ApiEndpointSelector.class
      )
      .setFields(
        new List<Schema.SObjectField>{
          CoreLibs_ApiEndpoint__mdt.EndpointRegex__c,
          CoreLibs_ApiEndpoint__mdt.ResolverClassName__c
        }
      );
    for (CoreLibs_ApiEndpoint__mdt endpoint : (List<CoreLibs_ApiEndpoint__mdt>) selector.getAll()) {
      if (Pattern.matches(endpoint.EndpointRegex__c, this.req.requestURI)) {
        return ((CoreLibs_ApiEndpointResolver) Type.forName(endpoint.ResolverClassName__c).newInstance())
          .setRequest(req);
      }
    }
    throw new CoreLibs_ApiExceptions.NotFoundException(
      String.format(ENDPOINT_NOT_FOUND, new List<String>{ this.req.requestURI })
    );
  }
}