force-app/logging/objects/CoreLibs_Log__c/CoreLibs_Log__c.object-meta.xml
<CustomObject>
    <description>Persisted log record for capturing metrics, errors, and other logging information in Salesforce.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>The details of the log as JSON.</description>
    <inlineHelpText>The details of the log as JSON.</inlineHelpText>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/logging/objects/CoreLibs_Log__c/fields/LogCreationTimestamp__c.field-meta.xml
<CustomField>
    <fullName>LogCreationTimestamp__c</fullName>
    <description>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</description>
    <inlineHelpText>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</inlineHelpText>
    <label>Log Creation Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/logging/objects/CoreLibs_Log__c/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user executing the transaction in which the log was generated.</description>
    <inlineHelpText>The user executing the transaction in which the log was generated.</inlineHelpText>
    <label>Running User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/logging/objects/CoreLibs_Log__c/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <description>The session Id for the user that executed the transaction in which the log was generated.</description>
    <inlineHelpText>The session Id for the user that executed the transaction in which the log was generated.</inlineHelpText>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_Log__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>The UUID generated for the transaction in which this log was generated.</description>
    <inlineHelpText>The UUID generated for the transaction in which this log was generated.</inlineHelpText>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of log e.g. ERROR, WARN, INFO.</description>
    <inlineHelpText>The type of log e.g. ERROR, WARN, INFO.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/CoreLibs_LogCleanupSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Cleanup Settings for logs</description>
    <label>Log Cleanup Settings</label>
</CustomObject>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/fields/RetainLogsFor__c.field-meta.xml
<CustomField>
    <fullName>RetainLogsFor__c</fullName>
    <description>How long to retain logs for.</description>
    <inlineHelpText>How long to retain logs for.</inlineHelpText>
    <label>Retain Logs For</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/fields/ScheduledTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledTime__c</fullName>
    <description>The scheduled time for the job. Stored as a convenience lookup. Runs risk of being out of sync with actual scheduled job.</description>
    <inlineHelpText>The scheduled time for the job. Stored as a convenience lookup. Runs risk of being out of sync with actual scheduled job.</inlineHelpText>
    <label>Scheduled Time</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/logging/classes/tests/CoreLibs_LogControllerTest.cls
@IsTest
private inherited sharing class CoreLibs_LogControllerTest {
  @IsTest
  private static void getLogDetails_mockedSelector_returnDetails() {
    mockSelectors();
    CoreLibs_SObjectMocker logMocker = new CoreLibs_SObjectMocker(CoreLibs_Log__c.getSObjectType());
    System.Test.startTest();
    String result = CoreLibs_LogController.getLogDetails(logMocker.generateMockId());
    System.Test.stopTest();
    Assert.areEqual('test', result, 'Should return log details');
  }

  @IsTest
  private static void getLogs_allInputs_inputsProcessedCorrectly() {
    CoreLibs_ClassMocker mocker = mockSelectors();
    CoreLibs_LogController.GetLogsInput input = new CoreLibs_LogController.GetLogsInput();
    input.transactionId = '123';
    input.runningUserId = UserInfo.getUserId();
    input.runningUserSessionId = 'cake';
    input.type = 'INFO';
    input.startTime = '2020-01-01T00:00:000z';
    input.endTime = '2020-01-01T00:00:000z';
    System.Test.startTest();
    List<CoreLibs_Log__c> results = CoreLibs_LogController.getLogs(input);
    System.Test.stopTest();
    List<String> args = new List<String>{
      'TransactionId__c = \'123\'',
      'RunningUser__c = \'' +
      UserInfo.getUserId() +
      '\'',
      'SessionId__c = \'cake\'',
      'LogCreationTimestamp__c >= 2020-01-01T00:00:000z',
      'LogCreationTimestamp__c <= 2020-01-01T00:00:000z',
      'Type__c = \'INFO\''
    };
    mocker.expectMethod('getByFilters').withArgs(new List<Object>{ args }).toHaveBeenCalled(1);
  }

  @IsTest
  private static void getLogCleanupSettings_mockedJob_returnSettings() {
    mockSelectors();
    System.Test.startTest();
    CoreLibs_LogController.GetLogCleanupSettingsOutput results = CoreLibs_LogController.getLogCleanupSettings();
    System.Test.stopTest();
    Assert.areEqual('Completed', results.lastRunStatus, 'Should appropriately set the status from the job');
  }

  // cant mock logger services because it accepts an exception as an arg
  // and Apex is a trash language

  @IsTest
  private static void saveRetainLogsForSetting_mockedService_confirmServiceCalled() {
    System.Test.startTest();
    CoreLibs_LogController.saveRetainLogsForSetting(7);
    System.Test.stopTest();
    CoreLibs_LogCleanupSettings__c settings = CoreLibs_LogCleanupSettings__c.getOrgDefaults();
    Assert.areEqual(7, settings.RetainLogsFor__c, 'Should set log retention');
  }

  @IsTest
  private static void scheduleLogCleanupJob_mockedService_confirmServiceCalled() {
    System.Test.startTest();
    CoreLibs_LogController.scheduleLogCleanupJob(7);
    System.Test.stopTest();
    CoreLibs_LogCleanupSettings__c settings = CoreLibs_LogCleanupSettings__c.getOrgDefaults();
    Assert.areEqual(7, settings.ScheduledTime__c, 'Should set scheduled time');
  }

  private static CoreLibs_ClassMocker mockSelectors() {
    CoreLibs_ClassMocker selectorMocker = new CoreLibs_ClassMocker()
      .whenInvoking('setFields')
      .fromClass(CoreLibs_LogSelector.class)
      .thenReturnInvokingObject(CoreLibs_LogSelector.class)
      .whenInvoking('setFields')
      .fromClass(CoreLibs_AsyncApexJobSelector.class)
      .thenReturnInvokingObject(CoreLibs_AsyncApexJobSelector.class)
      .whenInvoking('setOrderBy')
      .thenReturnInvokingObject(CoreLibs_LogSelector.class)
      .whenInvoking('setLimit')
      .thenReturnInvokingObject(CoreLibs_LogSelector.class)
      .whenInvoking('getById')
      .thenReturn(new List<SObject>{ new CoreLibs_Log__c(Details__c = 'test') })
      .whenInvoking('getByFilters')
      .thenReturn(new List<SObject>{ new CoreLibs_Log__c() })
      .whenInvoking('getLastCompletedJob')
      .thenReturn((AsyncApexJob) JSON.deserialize('{"Status":"Completed"}', AsyncApexJob.class));
    CoreLibs_ClassMocker factoryMocker = new CoreLibs_ClassMocker()
      .whenInvoking('create')
      .thenExecute(new CoreLibs_FactoryMethodMock(selectorMocker));
    CoreLibs_Factories.selector = (CoreLibs_SelectorFactory) factoryMocker.generateStub(CoreLibs_SelectorFactory.class);
    return selectorMocker;
  }
}