force-app/logging/objects/CoreLibs_Log__c/CoreLibs_Log__c.object-meta.xml
<CustomObject>
    <description>Persisted log record for capturing metrics, errors, and other logging information in Salesforce.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_Log__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>The details of the log as JSON.</description>
    <inlineHelpText>The details of the log as JSON.</inlineHelpText>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/logging/objects/CoreLibs_Log__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The label for the log.</description>
    <inlineHelpText>The label for the log.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of log e.g. ERROR, WARN, INFO.</description>
    <inlineHelpText>The type of log e.g. ERROR, WARN, INFO.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/logging/classes/tests/CoreLibs_LightningLoggerTest.cls
@IsTest
private inherited sharing class CoreLibs_LightningLoggerTest {
  @IsTest
  private static void info_simpleInput_createLogRecord() {
    System.Test.startTest();
    CoreLibs_LightningLogger.info('TEST LOG INFO', new Map<String, Object>{ 'message' => 'Hello World' });
    System.Test.stopTest();
    CoreLibs_Log__c log = [SELECT Label__c, Type__c, Details__c FROM CoreLibs_Log__c];
    Assert.areEqual('TEST LOG INFO', log.Label__c, 'Should set label');
    Assert.areEqual('INFO', log.Type__c, 'Should set type');
    Assert.isTrue(log.Details__c.contains('"Hello World"'), 'Should set details');
  }

  @IsTest
  private static void warn_simpleInput_createLogRecord() {
    System.Test.startTest();
    CoreLibs_LightningLogger.warn('TEST LOG WARN', new Map<String, Object>{ 'message' => 'Hello World' });
    System.Test.stopTest();
    CoreLibs_Log__c log = [SELECT Label__c, Type__c, Details__c FROM CoreLibs_Log__c];
    Assert.areEqual('TEST LOG WARN', log.Label__c, 'Should set label');
    Assert.areEqual('WARN', log.Type__c, 'Should set type');
    Assert.isTrue(log.Details__c.contains('"Hello World"'), 'Should set details');
  }

  @IsTest
  private static void error_simpleInput_createLogRecord() {
    System.Test.startTest();
    CoreLibs_LightningLogger.error('TEST LOG ERROR', new Map<String, Object>{ 'message' => 'Hello World' });
    System.Test.stopTest();
    CoreLibs_Log__c log = [SELECT Label__c, Type__c, Details__c FROM CoreLibs_Log__c];
    Assert.areEqual('TEST LOG ERROR', log.Label__c, 'Should set label');
    Assert.areEqual('ERROR', log.Type__c, 'Should set type');
    Assert.isTrue(log.Details__c.contains('"Hello World"'), 'Should set details');
  }
}