force-app/logging/objects/CoreLibs_Log__c/CoreLibs_Log__c.object-meta.xml
<CustomObject>
    <description>Persisted log record for capturing metrics, errors, and other logging information in Salesforce.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_Log__c/fields/LogCreationTimestamp__c.field-meta.xml
<CustomField>
    <fullName>LogCreationTimestamp__c</fullName>
    <description>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</description>
    <inlineHelpText>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</inlineHelpText>
    <label>Log Creation Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/CoreLibs_LogCleanupSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Cleanup Settings for logs</description>
    <label>Log Cleanup Settings</label>
</CustomObject>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/fields/RetainLogsFor__c.field-meta.xml
<CustomField>
    <fullName>RetainLogsFor__c</fullName>
    <description>How long to retain logs for.</description>
    <inlineHelpText>How long to retain logs for.</inlineHelpText>
    <label>Retain Logs For</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/logging/classes/tests/CoreLibs_LogCleanupJobTest.cls
@IsTest
private inherited sharing class CoreLibs_LogCleanupJobTest {
  @IsTest
  private static void e2e_1ToRetain_deleteAllButOne() {
    CoreLibs_Log__c toKeep = new CoreLibs_Log__c(LogCreationTimestamp__c = Datetime.now());
    CoreLibs_log__c toDelete = new CoreLibs_Log__c(LogCreationTimestamp__c = Datetime.now().addDays(-7));
    insert new List<CoreLibs_Log__c>{ toKeep, toDelete };
    CoreLibs_LogCleanupSettings__c settings = CoreLibs_LogCleanupSettings__c.getOrgDefaults();
    settings.RetainLogsFor__c = 3;
    upsert settings;
    CoreLibs_LogCleanupJob job = new CoreLibs_LogCleanupJob();
    System.Test.startTest();
    Database.executeBatch(job);
    System.Test.stopTest();
    CoreLibs_Log__c remaining = [SELECT Id FROM CoreLibs_Log__c];
    Assert.areEqual(toKeep.Id, remaining.Id, 'Should keep the correct log');
  }
}