force-app/logging/objects/CoreLibs_Log__c/CoreLibs_Log__c.object-meta.xml
<CustomObject>
    <description>Persisted log record for capturing metrics, errors, and other logging information in Salesforce.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG-{0}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_Log__c/fields/LogCreationTimestamp__c.field-meta.xml
<CustomField>
    <fullName>LogCreationTimestamp__c</fullName>
    <description>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</description>
    <inlineHelpText>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</inlineHelpText>
    <label>Log Creation Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/CoreLibs_LogCleanupSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Cleanup Settings for logs</description>
    <label>Log Cleanup Settings</label>
</CustomObject>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/fields/RetainLogsFor__c.field-meta.xml
<CustomField>
    <fullName>RetainLogsFor__c</fullName>
    <description>How long to retain logs for.</description>
    <inlineHelpText>How long to retain logs for.</inlineHelpText>
    <label>Retain Logs For</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/logging/classes/CoreLibs_LogCleanupJob.cls
/**
 * @description Cleanup jobs for logs in Salesforce
 * @author Tom Wilkins
 * @group Logging
 */
public without sharing class CoreLibs_LogCleanupJob implements Database.Batchable<SObject>, System.Schedulable {
  @TestVisible
  private static final String JOB_NAME = 'Log Cleanup Job';
  @TestVisible
  private static final String CRON = '0 0 {0} * * ? *';

  /**
   * @description Schedules the job to operate daily at the provided hour
   * @param hour The hour to execute at
   */
  public static void schedule(Integer hour) {
    cancel();
    System.schedule(
      JOB_NAME,
      String.format(CRON, new List<String>{ String.valueOf(hour) }),
      new CoreLibs_LogCleanupJob()
    );
  }

  /**
   * @description Cancels an existing log cleanup job
   */
  public static void cancel() {
    CoreLibs_CronTriggerSelector cronSelector = (CoreLibs_CronTriggerSelector) CoreLibs_Factories.selector.create(
      CoreLibs_CronTriggerSelector.class
    );
    List<CronTrigger> existingJobs = cronSelector.getByJobName(new Set<String>{ JOB_NAME });
    if (!existingJobs.isEmpty()) {
      for (CronTrigger job : existingJobs) {
        System.abortJob(job.Id);
      }
    }
  }

  public Database.QueryLocator start(Database.BatchableContext ctx) {
    CoreLibs_LogCleanupSettings__c settings = CoreLibs_LogCleanupSettings__c.getOrgDefaults();
    Datetime cutoff;
    if (settings.RetainLogsFor__c != null) {
      cutoff = Datetime.now().addDays(-((Integer) settings.RetainLogsFor__c));
    } else {
      // default to 30 days if no setting
      cutoff = Datetime.now().addDays(-30);
    }
    String query = 'SELECT Id FROM CoreLibs_Log__c WHERE LogCreationTimestamp__c <= :cutoff';
    return Database.getQueryLocator(query);
  }

  public void execute(Database.BatchableContext ctx, List<SObject> records) {
    delete records;
  }

  public void finish(Database.BatchableContext ctx) {
    return;
  }

  public void execute(System.SchedulableContext ctx) {
    Database.executeBatch(this);
  }
}