force-app/env/objects/CoreLibs_EnvVariables__c/CoreLibs_EnvVariables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Environment variables for use in various applications</description>
    <label>Environment Variables</label>
</CustomObject>

force-app/env/objects/CoreLibs_EnvVariables__c/fields/CoreLibs_IdempotentEntryTTL__c.field-meta.xml
<CustomField>
    <fullName>CoreLibs_IdempotentEntryTTL__c</fullName>
    <defaultValue>7</defaultValue>
    <description>TTL for idempotent entries for apis.</description>
    <inlineHelpText>TTL for idempotent entries for apis.</inlineHelpText>
    <label>IdempotentEntryTTL</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/CoreLibs_IdempotentEntry__c.object-meta.xml
<CustomObject>
    <description>Entry that is used for idempotency enabled endpoints</description>
    <label>Idempotent Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Idempotent Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idempotent Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/api/classes/CoreLibs_IdempotentEntryCleanupJob.cls
/**
 * @description Job for cleaning up API Requests after they have lived beyond some configurable TTL
 * @author Tom Wilkins
 * @group Api
 */
public without sharing class CoreLibs_IdempotentEntryCleanupJob implements Database.Batchable<sObject> {
  @TestVisible
  private Integer ttlInDays;

  public CoreLibs_IdempotentEntryCleanupJob() {
    CoreLibs_EnvVariables__c env = CoreLibs_EnvVariables__c.getOrgDefaults();
    if (env.CoreLibs_IdempotentEntryTTL__c == null) {
      this.ttlInDays = 7;
    } else {
      this.ttlInDays = Integer.valueOf(env.CoreLibs_IdempotentEntryTTL__c);
    }
  }

  public Database.Querylocator start(Database.BatchableContext BC) {
    Datetime dt = Datetime.now().addDays(-(this.ttlInDays));
    return Database.getQueryLocator('SELECT Id FROM CoreLibs_IdempotentEntry__c WHERE CreatedDate <= :dt');
  }

  public void execute(Database.BatchableContext info, List<SObject> scope) {
    CoreLibs_DataSettings.getInstance().disableFLS();
    CoreLibs_Services.dml.deleteRecords(scope);
  }

  public void finish(Database.BatchableContext BC) {
  }
}