force-app/env/objects/CoreLibs_EnvVariables__c/CoreLibs_EnvVariables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Environment variables for use in various applications</description>
    <label>Environment Variables</label>
</CustomObject>

force-app/env/objects/CoreLibs_EnvVariables__c/fields/CoreLibs_DevTeamEmail__c.field-meta.xml
<CustomField>
    <fullName>CoreLibs_DevTeamEmail__c</fullName>
    <description>Email address for the dev team. Used for dev team communications.</description>
    <inlineHelpText>Email address for the dev team. Used for dev team communications.</inlineHelpText>
    <label>Dev Team Email</label>
    <type>Email</type>
</CustomField>

force-app/email/classes/tests/CoreLibs_DevTeamEmailTest.cls
@IsTest
private inherited sharing class CoreLibs_DevTeamEmailTest {
  @IsTest
  private static void sendEmail_coverage() {
    CoreLibs_EnvVariables__c env = CoreLibs_EnvVariables__c.getOrgDefaults();
    env.CoreLibs_DevTeamEmail__c = 'apexunittest@ultra.me';
    insert env;
    CoreLibs_DevTeamEmail em = new CoreLibs_DevTeamEmail();
    System.Test.startTest();
    em.sendEmail('Test', 'Test');
    System.Test.stopTest();
    // because the email will not fire and we dont have a service wrapper to mock
    // then just verify that the test executes
    Assert.isTrue(true, 'Method should execution');
  }
}