force-app/logging/objects/CoreLibs_MonitoringRule__c/CoreLibs_MonitoringRule__c.object-meta.xml
<CustomObject>
    <description>Object for storing rules that execute monitoring activities on the Salesforce platform.</description>
    <label>Salesforce Monitoring Rule</label>
    <nameField>
        <label>Monitoring Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_MonitoringRule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the rule is active.</description>
    <inlineHelpText>Whether or not the rule is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/logging/classes/CoreLibs_MonitoringRuleSelector.cls
/**
 * @description Data access layer ofr Salesforce monitoring rules
 * @author Tom Wilkins
 * @group Logging
 */
public inherited sharing class CoreLibs_MonitoringRuleSelector extends CoreLibs_BaseSelector {
  public override Schema.SObjectType getSObjectType() {
    return CoreLibs_MonitoringRule__c.getSObjectType();
  }

  /**
   * @description Queries all active monitoring rules
   * @return List of active rules
   */
  public List<CoreLibs_MonitoringRule__c> getActiveRules() {
    return (List<CoreLibs_MonitoringRule__c>) Database.query(this.buildQueryString('IsActive__c = true'));
  }
}