force-app/logging/objects/CoreLibs_MonitoringRule__c/CoreLibs_MonitoringRule__c.object-meta.xml
<CustomObject>
    <description>Object for storing rules that execute monitoring activities on the Salesforce platform.</description>
    <label>Salesforce Monitoring Rule</label>
    <nameField>
        <label>Monitoring Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_MonitoringRule__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the rule is active.</description>
    <inlineHelpText>Whether or not the rule is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/logging/classes/tests/CoreLibs_MonitoringRuleSelectorTest.cls
@IsTest
private inherited sharing class CoreLibs_MonitoringRuleSelectorTest {
  @IsTest
  private static void getSObjectType_SalesforceMonitoringRule() {
    CoreLibs_MonitoringRuleSelector selector = new CoreLibs_MonitoringRuleSelector();
    System.Test.startTest();
    Schema.SObjectType result = selector.getSObjectType();
    System.Test.stopTest();
    Assert.areEqual(CoreLibs_MonitoringRule__c.getSObjectType(), result, 'Should return CoreLibs_MonitoringRule__c');
  }

  @IsTest
  private static void getActiveRules_1Active1Inactive_return1() {
    List<CoreLibs_MonitoringRule__c> rules = new List<CoreLibs_MonitoringRule__c>{
      new CoreLibs_MonitoringRule__c(IsActive__c = true),
      new CoreLibs_MonitoringRule__c(IsActive__c = false)
    };
    insert rules;
    CoreLibs_MonitoringRuleSelector selector = new CoreLibs_MonitoringRuleSelector();
    System.Test.startTest();
    List<CoreLibs_MonitoringRule__c> result = selector.getActiveRules();
    System.Test.stopTest();
    Assert.areEqual(1, result.size(), 'Should return the 1 active record');
  }
}