force-app/logging/objects/CoreLibs_MonitoringRule__c/CoreLibs_MonitoringRule__c.object-meta.xml
<CustomObject>
    <description>Object for storing rules that execute monitoring activities on the Salesforce platform.</description>
    <label>Salesforce Monitoring Rule</label>
    <nameField>
        <label>Monitoring Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_MonitoringRule__c/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <formula>IF(
  NOT(ISBLANK(CustomClass__c)), 
  CustomClass__c,
  CASE(RecordType.DeveloperName , 
  &apos;QueryRule&apos;, &apos;QueryRuleProcessor&apos;,
  &apos;&apos;
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Class Name</label>
    <type>Text</type>
</CustomField>

force-app/logging/classes/CoreLibs_MonitoringRuleProcessor.cls
/**
 * @description Base class for monitoring rule processesors. Note that when creating new
 * processor types, there may be additional configuration in the ClassName__c field on
 * the CoreLibs_MonitoringRule__c object
 * @author Tom Wilkins
 * @group Logging
 */
public inherited sharing abstract class CoreLibs_MonitoringRuleProcessor {
  @TestVisible
  protected CoreLibs_MonitoringRule__c rule;
  @TestVisible
  protected Datetime lastRun;

  /**
   * @description Monitor logic method
   */
  public abstract void execute();

  /**
   * @description Rule setter
   * @param rule Rule to set
   * @return Reference to the invoking object
   */
  public CoreLibs_MonitoringRuleProcessor setRule(CoreLibs_MonitoringRule__c rule) {
    this.rule = rule;
    return this;
  }

  /**
   * @description Sets the last time the job was run
   * @param lastRun Last time job was run
   * @return Reference to the invoking object
   */
  public CoreLibs_MonitoringRuleProcessor setLastRun(Datetime lastRun) {
    this.lastRun = lastRun;
    return this;
  }
}