force-app/logging/objects/CoreLibs_MonitoringAlert__c/CoreLibs_MonitoringAlert__c.object-meta.xml
<CustomObject>
    <description>Alert triggered by monitoring framework.</description>
    <label>Monitoring Alert</label>
    <nameField>
        <displayFormat>MA-{0}</displayFormat>
        <label>Monitoring Alert Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monitoring Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_MonitoringRule__c/CoreLibs_MonitoringRule__c.object-meta.xml
<CustomObject>
    <description>Object for storing rules that execute monitoring activities on the Salesforce platform.</description>
    <label>Salesforce Monitoring Rule</label>
    <nameField>
        <label>Monitoring Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monitoring Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/logging/objects/CoreLibs_MonitoringRule__c/fields/QueryFilter__c.field-meta.xml
<CustomField>
    <fullName>QueryFilter__c</fullName>
    <description>Query filter used to return record counts to measure against the threshold.</description>
    <inlineHelpText>Query filter used to return record counts to measure against the threshold.</inlineHelpText>
    <label>Query Filter</label>
    <type>TextArea</type>
</CustomField>

force-app/logging/objects/CoreLibs_MonitoringRule__c/fields/QuerySObjectType__c.field-meta.xml
<CustomField>
    <fullName>QuerySObjectType__c</fullName>
    <description>The SObject that the query rule should run against.</description>
    <inlineHelpText>The SObject that the query rule should run against.</inlineHelpText>
    <label>Query SObject Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_MonitoringRule__c/fields/RecordCountThreshold__c.field-meta.xml
<CustomField>
    <fullName>RecordCountThreshold__c</fullName>
    <description>The threshold at which an alert should be created once exceeded.</description>
    <inlineHelpText>The threshold at which an alert should be created once exceeded.</inlineHelpText>
    <label>Record Count Threshold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/logging/classes/tests/CoreLibs_QueryRuleProcessorTest.cls
@IsTest
private inherited sharing class CoreLibs_QueryRuleProcessorTest {
  @TestSetup
  private static void makeData() {
    Account acct1 = new Account(Name = 'Test');
    Account acct2 = new Account(Name = 'Other');
    insert new List<Account>{ acct1, acct2 };
  }
  @IsTest
  private static void execute_ruleNotTriggered_noAlert() {
    CoreLibs_QueryRuleProcessor processor = new CoreLibs_QueryRuleProcessor();
    processor.lastRun = Datetime.now().addHours(-1);
    processor.rule = new CoreLibs_MonitoringRule__c(
      QuerySObjectType__c = 'Account',
      QueryFilter__c = 'Name = \'Not Found\'',
      RecordCountThreshold__c = 1
    );
    System.Test.startTest();
    processor.execute();
    System.Test.stopTest();
    Assert.areEqual(0, [SELECT Id FROM CoreLibs_MonitoringAlert__c].size(), 'Should not create an alert');
  }

  @IsTest
  private static void execute_ruleTriggered_alertCreated() {
    CoreLibs_QueryRuleProcessor processor = new CoreLibs_QueryRuleProcessor();
    processor.lastRun = Datetime.now().addHours(-1);
    processor.rule = new CoreLibs_MonitoringRule__c(
      QuerySObjectType__c = 'Account',
      QueryFilter__c = 'Name = \'Test\'',
      RecordCountThreshold__c = 1
    );
    System.Test.startTest();
    processor.execute();
    System.Test.stopTest();
    Assert.areEqual(1, [SELECT Id FROM CoreLibs_MonitoringAlert__c].size(), 'Should create an alert');
  }
}