force-app/core/objects/CoreLibs_ErrorCodeToUIMessageMapping__mdt/CoreLibs_ErrorCodeToUIMessageMapping__mdt.object-meta.xml
<CustomObject>
    <description>Configuration for mapping error codes to UI messages.</description>
    <label>Error Code to UI Message Mapping</label>
    <pluralLabel>Error Code to UI Message Mappings</pluralLabel>
</CustomObject>

force-app/core/objects/CoreLibs_ErrorCodeToUIMessageMapping__mdt/fields/ErrorCode__c.field-meta.xml
<CustomField>
    <fullName>ErrorCode__c</fullName>
    <description>Error code to map.</description>
    <inlineHelpText>Error code to map.</inlineHelpText>
    <label>Error Code</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/core/classes/CoreLibs_ErrorCodeToUIMappingSelector.cls
/**
 * @description Data access class for the CoreLibs_ErrorCodeToUIMessageMapping__mdt object
 * @author Tom Wilkins
 */
public inherited sharing class CoreLibs_ErrorCodeToUIMappingSelector extends CoreLibs_BaseSelector {
  public override Schema.SObjectType getSObjectType() {
    return CoreLibs_ErrorCodeToUIMessageMapping__mdt.getSObjectType();
  }

  /**
   * @description Returns the relevant mappings for the provided error codes
   * @param errorCodes error codes to retrieve mappings fr
   * @return Results from the query
   */
  public List<CoreLibs_ErrorCodeToUIMessageMapping__mdt> getByErrorCodes(Set<String> errorCodes) {
    return (List<CoreLibs_ErrorCodeToUIMessageMapping__mdt>) Database.query(
      this.buildQueryString('ErrorCode__c IN :errorCodes')
    );
  }
}