force-app/api/objects/CoreLibs_IdempotentEntry__c/CoreLibs_IdempotentEntry__c.object-meta.xml
<CustomObject>
    <description>Entry that is used for idempotency enabled endpoints</description>
    <label>Idempotent Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Idempotent Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idempotent Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/IdempotencyKey__c.field-meta.xml
<CustomField>
    <fullName>IdempotencyKey__c</fullName>
    <description>The Idempotency key used to guarantee that redundant requests aren&apos;t processed.</description>
    <externalId>true</externalId>
    <inlineHelpText
  >The Idempotency key used to guarantee that redundant requests aren&apos;t processed.</inlineHelpText>
    <label>Idempotency Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/api/classes/CoreLibs_IdempotentEntrySelector.cls
/**
 * @description Data access class for idempotent keys
 * @author Tom Wilkins
 * @group Api
 */
public inherited sharing class CoreLibs_IdempotentEntrySelector extends CoreLibs_BaseSelector {
  public override Schema.SObjectType getSObjectType() {
    return CoreLibs_IdempotentEntry__c.getSObjectType();
  }

  /**
   * @description Returns requests by their idempotency keys
   * @param idempotencyKeys Request keys to filter on
   * @return List of api requests
   */
  public List<CoreLibs_IdempotentEntry__c> getByIdempotencyKey(Set<String> idempotencyKeys) {
    return Database.query(this.buildQueryString('IdempotencyKey__c IN :idempotencyKeys'));
  }
}