force-app/api/objects/CoreLibs_IdempotentEntry__c/CoreLibs_IdempotentEntry__c.object-meta.xml
<CustomObject>
    <description>Entry that is used for idempotency enabled endpoints</description>
    <label>Idempotent Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Idempotent Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idempotent Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>The method of the HTTP request.</description>
    <inlineHelpText>The method of the HTTP request.</inlineHelpText>
    <label>Http Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>PATCH</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/IdempotencyKey__c.field-meta.xml
<CustomField>
    <fullName>IdempotencyKey__c</fullName>
    <description>The Idempotency key used to guarantee that redundant requests aren&apos;t processed.</description>
    <externalId>true</externalId>
    <inlineHelpText
  >The Idempotency key used to guarantee that redundant requests aren&apos;t processed.</inlineHelpText>
    <label>Idempotency Key</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatusCode__c</fullName>
    <description>Status code for the response.</description>
    <inlineHelpText>Status code for the response.</inlineHelpText>
    <label>Response Status Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <description>Fully qualified URL for the endpoint being hit.</description>
    <inlineHelpText>Fully qualified URL for the endpoint being hit.</inlineHelpText>
    <label>Url</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/api/classes/tests/CoreLibs_IdempotentEntrySelectorTest.cls
@IsTest
private inherited sharing class CoreLibs_IdempotentEntrySelectorTest {
  @IsTest
  private static void getSObjectType_IdempotentEntry() {
    CoreLibs_IdempotentEntrySelector reqSelector = new CoreLibs_IdempotentEntrySelector();
    System.Test.startTest();
    Schema.SObjectType result = reqSelector.getSObjectType();
    System.Test.stopTest();
    Assert.areEqual(
      CoreLibs_IdempotentEntry__c.getSObjectType(),
      result,
      'Should return the CoreLibs_IdempotentEntry__c sobject type'
    );
  }

  @IsTest
  private static void getByIdempotencyKey_multipleEntries_returnOne() {
    CoreLibs_IdempotentEntry__c req1 = new CoreLibs_IdempotentEntry__c(
      HttpMethod__c = 'POST',
      Url__c = 'test',
      IdempotencyKey__c = 'abc123',
      ResponseStatusCode__c = '200'
    );
    CoreLibs_IdempotentEntry__c req2 = new CoreLibs_IdempotentEntry__c(
      HttpMethod__c = 'POST',
      Url__c = 'test',
      IdempotencyKey__c = '456xyz',
      ResponseStatusCode__c = '200'
    );
    insert new List<CoreLibs_IdempotentEntry__c>{ req1, req2 };
    CoreLibs_IdempotentEntrySelector reqSelector = new CoreLibs_IdempotentEntrySelector();
    System.Test.startTest();
    List<CoreLibs_IdempotentEntry__c> results = reqSelector.getByIdempotencyKey(new Set<String>{ 'abc123' });
    System.Test.stopTest();
    Assert.areEqual(1, results.size(), 'Should return one entry record');
    Assert.areEqual(req1.Id, results[0].Id, 'Should return the correct entry record');
  }
}