force-app/api/objects/CoreLibs_IdempotentEntry__c/CoreLibs_IdempotentEntry__c.object-meta.xml
<CustomObject>
    <description>Entry that is used for idempotency enabled endpoints</description>
    <label>Idempotent Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Idempotent Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idempotent Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <description>Response details for the incoming request.</description>
    <inlineHelpText>Response details for the incoming request.</inlineHelpText>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>ResponseHeaders__c</fullName>
    <description>Response header details for the incoming request.</description>
    <inlineHelpText>Response header details for the incoming request.</inlineHelpText>
    <label>Response Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatusCode__c</fullName>
    <description>Status code for the response.</description>
    <inlineHelpText>Status code for the response.</inlineHelpText>
    <label>Response Status Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/api/classes/CoreLibs_IdempotentApiResponse.cls
/**
 * @description Data selector class for Api_Endpoint__mdt custom metadata
 * @author Tom Wilkins
 * @group Api
 */
public with sharing class CoreLibs_IdempotentApiResponse implements CoreLibs_IApiResponse {
  @TestVisible
  private CoreLibs_IdempotentEntry__c entry;

  /**
   * @description Constructor
   * @param entry The Idempotent entry record to generate the response from
   */
  public CoreLibs_IdempotentApiResponse(CoreLibs_IdempotentEntry__c entry) {
    this.entry = entry;
  }

  /**
   * @see {@link CoreLibs_IApiResponse}
   */
  public System.RestResponse toResponse() {
    RestResponse res = RestContext.response;
    res.statusCode = Integer.valueOf(this.entry.ResponseStatusCode__c);
    res.responseBody = Blob.valueOf(this.entry.ResponseBody__c);
    Map<String, String> headers = (Map<String, String>) JSON.deserialize(
      this.entry.ResponseHeaders__c,
      Map<String, String>.class
    );
    for (String header : headers.keySet()) {
      res.addHeader(header, headers.get(header));
    }
    return res;
  }
}