force-app/api/objects/CoreLibs_IdempotentEntry__c/CoreLibs_IdempotentEntry__c.object-meta.xml
<CustomObject>
    <description>Entry that is used for idempotency enabled endpoints</description>
    <label>Idempotent Entry</label>
    <nameField>
        <displayFormat>IE-{000000}</displayFormat>
        <label>Idempotent Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Idempotent Entries</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/ResponseBody__c.field-meta.xml
<CustomField>
    <fullName>ResponseBody__c</fullName>
    <description>Response details for the incoming request.</description>
    <inlineHelpText>Response details for the incoming request.</inlineHelpText>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>ResponseHeaders__c</fullName>
    <description>Response header details for the incoming request.</description>
    <inlineHelpText>Response header details for the incoming request.</inlineHelpText>
    <label>Response Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/api/objects/CoreLibs_IdempotentEntry__c/fields/ResponseStatusCode__c.field-meta.xml
<CustomField>
    <fullName>ResponseStatusCode__c</fullName>
    <description>Status code for the response.</description>
    <inlineHelpText>Status code for the response.</inlineHelpText>
    <label>Response Status Code</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/api/classes/tests/CoreLibs_IdempotentApiResponseTest.cls
@IsTest
private inherited sharing class CoreLibs_IdempotentApiResponseTest {
  @IsTest
  private static void toResponse_fromRecord_returnResponse() {
    RestContext.response = new RestResponse();
    CoreLibs_IdempotentEntry__c req = new CoreLibs_IdempotentEntry__c(
      ResponseStatusCode__c = '201',
      ResponseBody__c = '{"Test":"Value"}',
      ResponseHeaders__c = '{"Key":"Value"}'
    );
    CoreLibs_IdempotentApiResponse res = new CoreLibs_IdempotentApiResponse(req);
    System.Test.startTest();
    RestResponse result = res.toResponse();
    System.Test.stopTest();
    Assert.areEqual(201, result.statusCode, 'Should set status to 201');
    Assert.areEqual('{"Test":"Value"}', result.responseBody.toString(), 'Should set the body');
    Assert.areEqual('Value', result.headers.get('Key'), 'Should set the headers');
  }
}