force-app/logging/objects/CoreLibs_LogCleanupSettings__c/CoreLibs_LogCleanupSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Cleanup Settings for logs</description>
    <label>Log Cleanup Settings</label>
</CustomObject>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/fields/RetainLogsFor__c.field-meta.xml
<CustomField>
    <fullName>RetainLogsFor__c</fullName>
    <description>How long to retain logs for.</description>
    <inlineHelpText>How long to retain logs for.</inlineHelpText>
    <label>Retain Logs For</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogCleanupSettings__c/fields/ScheduledTime__c.field-meta.xml
<CustomField>
    <fullName>ScheduledTime__c</fullName>
    <description>The scheduled time for the job. Stored as a convenience lookup. Runs risk of being out of sync with actual scheduled job.</description>
    <inlineHelpText>The scheduled time for the job. Stored as a convenience lookup. Runs risk of being out of sync with actual scheduled job.</inlineHelpText>
    <label>Scheduled Time</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/CoreLibs_LogEvent__e.object-meta.xml
<CustomObject>
    <description>Platform event that is emitted for any and all logging via the core logging library.</description>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>The details of the log as JSON.</description>
    <inlineHelpText>The details of the log as JSON.</inlineHelpText>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <description>The label for the log.</description>
    <inlineHelpText>The label for the log.</inlineHelpText>
    <label>Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/LogCreationTimestamp__c.field-meta.xml
<CustomField>
    <fullName>LogCreationTimestamp__c</fullName>
    <description>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</description>
    <inlineHelpText>Timestamp used for knowing when logs were generated. Necessary because createddate may not be accurate pending latency.</inlineHelpText>
    <label>Log Creation Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/RunningUser__c.field-meta.xml
<CustomField>
    <fullName>RunningUser__c</fullName>
    <description>The user executing the transaction in which the log was generated.</description>
    <inlineHelpText>The user executing the transaction in which the log was generated.</inlineHelpText>
    <label>Running User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/SessionId__c.field-meta.xml
<CustomField>
    <fullName>SessionId__c</fullName>
    <description>The session Id for the user that executed the transaction in which the log was generated.</description>
    <inlineHelpText>The session Id for the user that executed the transaction in which the log was generated.</inlineHelpText>
    <label>Session Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <description>The UUID generated for the transaction in which this log was generated.</description>
    <inlineHelpText>The UUID generated for the transaction in which this log was generated.</inlineHelpText>
    <label>Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/TransactionType__c.field-meta.xml
<CustomField>
    <fullName>TransactionType__c</fullName>
    <description>The type of transaction the log was captured in.</description>
    <inlineHelpText>The type of transaction the log was captured in.</inlineHelpText>
    <label>Transaction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/objects/CoreLibs_LogEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of log e.g. ERROR, WARN, INFO.</description>
    <inlineHelpText>The type of log e.g. ERROR, WARN, INFO.</inlineHelpText>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/logging/classes/CoreLibs_Logger.cls
/**
 * @description Logging interface for creating Salesforce logs
 * @author Tom Wilkins
 * @group Logging
 */
public inherited sharing class CoreLibs_Logger {
  @TestVisible
  private static final String ERROR_KEY = 'error';
  @TestVisible
  private static final String ERROR_MESSAGE_KEY = 'message';
  @TestVisible
  private static final String ERROR_STACKTRACE_KEY = 'stackTrace';
  @TestVisible
  private static final String ERROR_ADDITIONAL_DETAILS_KEY = 'additionalDetails';
  @TestVisible
  private static final String TYPE_ERROR = 'ERROR';
  @TestVisible
  private static final String TYPE_WARN = 'WARN';
  @TestVisible
  private static final String TYPE_INFO = 'INFO';

  /**
   * @description Creates an info log
   * @param label The label of the log
   * @param details The details to log
   */
  public void info(String label, Object details) {
    EventBus.publish(this.buildLog(label, TYPE_INFO, details));
  }

  /**
   * @description Creates a warn log
   * @param label The label of the log
   * @param details The details to log
   */
  public void warn(String label, Object details) {
    EventBus.publish(this.buildLog(label, TYPE_WARN, details));
  }

  /**
   * @description Creates an error log
   * @param label The label of the log
   * @param details The details to log
   */
  public void error(String label, Object details) {
    EventBus.publish(this.buildLog(label, TYPE_ERROR, details));
  }

  /**
   * @description Creates an error log
   * @param label The label of the log
   * @param e The exception to log details around
   */
  public void error(String label, Exception e) {
    Map<String, Object> details = new Map<String, Object>{
      ERROR_KEY => new Map<String, Object>{
        ERROR_MESSAGE_KEY => e.getMessage(),
        ERROR_STACKTRACE_KEY => e.getStackTraceString()
      }
    };
    EventBus.publish(this.buildLog(label, TYPE_ERROR, details));
  }

  /**
   * @description Creates an error log
   * @param label The label of the log
   * @param e The exception to log details around
   * @param additionalDetails Additional details to log with the exception
   */
  public void error(String label, Exception e, Object additionalDetails) {
    Map<String, Object> details = new Map<String, Object>{
      ERROR_KEY => new Map<String, Object>{
        ERROR_MESSAGE_KEY => e.getMessage(),
        ERROR_STACKTRACE_KEY => e.getStackTraceString()
      },
      ERROR_ADDITIONAL_DETAILS_KEY => additionalDetails
    };
    EventBus.publish(this.buildLog(label, TYPE_ERROR, details));
  }

  /**
   * @description Sets how long to retain logs for when a cleanup job is scheduled
   * @param numOfdays The number of days to retain a log for
   */
  public void setLogRetention(Integer numOfdays) {
    CoreLibs_LogCleanupSettings__c settings = CoreLibs_LogCleanupSettings__c.getOrgDefaults();
    settings.RetainLogsFor__c = numOfdays;
    upsert settings;
  }

  /**
   * @description Schedules a job to run daily at the time provided
   * Note this will run in the timezone of the person who schedules the job
   * @param scheduledTime Time to run job daily
   */
  public void scheduleDailyCleanup(Integer scheduledTime) {
    CoreLibs_LogCleanupSettings__c settings = CoreLibs_LogCleanupSettings__c.getOrgDefaults();
    settings.ScheduledTime__c = scheduledTime;
    upsert settings;
    CoreLibs_LogCleanupJob.schedule(scheduledTime);
  }

  @TestVisible
  private CoreLibs_LogEvent__e buildLog(String label, String type, Object details) {
    CoreLibs_LoggerContext ctx = CoreLibs_LoggerContext.getInstance();
    return new CoreLibs_LogEvent__e(
      Label__c = label,
      Type__c = type,
      Details__c = JSON.serialize(details),
      RunningUser__c = ctx.getRunningUserId(),
      SessionId__c = ctx.getRunningUserSessionId(),
      TransactionId__c = ctx.getTransactionId(),
      TransactionType__c = ctx.getTransactionType(),
      LogCreationTimestamp__c = Datetime.now()
    );
  }
}